root = "/randchat"
tmp_dir = "bin"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o /randchat/bin/messages-writer /randchat/cmd/messages-writer"
# Binary file yields from `cmd`.
bin = "./bin/messages-writer"
# Customize binary, can setup environment variables when run your app.
full_bin = "/randchat/bin/messages-writer"
# Watch these filename extensions.
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = []
# Watch these directories if you specified.
include_dir = [
  "cmd/messages-writer",
  "messages",
  "internal",
  "pkg",
]
# Exclude files.
exclude_file = [ ]
# Exclude specific regular expressions.
exclude_regex = [ ".*_test.go", ".*.yml", "*.out", "Makefile", "*.md" ]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1500 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 1500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true